#!/bin/bash

echo "🔧 Git Hook Bypass Utility"
echo ""
echo "This script provides commands to bypass git hooks when needed during development."
echo "⚠️  Use these commands carefully and ensure code quality before pushing!"
echo ""
echo "Available commands:"
echo ""
echo "1. Commit without pre-commit hooks:"
echo "   git commit --no-verify -m \"your message\""
echo ""
echo "2. Push without pre-push hooks:"
echo "   git push --no-verify"
echo ""
echo "3. Format all files quickly:"
echo "   npm run format"
echo ""
echo "4. Check formatting without fixing:"
echo "   npm run format:check"
echo ""
echo "5. Run tests quickly:"
echo "   npm run test:run"
echo ""
echo "💡 Tip: Always run 'npm run format' and 'npm run test:all' before pushing to main!" 