name: Manual Deploy to S3

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to deploy (e.g., 1.0.0)'
        required: true
        type: string

jobs:
  deploy-mac:
    runs-on: macos-latest
    timeout-minutes: 30
    environment: env  # 👈 Add this line

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Vite assets
        run: npm run build

      - name: Create dummy .env for CI build
        run: |
          echo "# Dummy .env file for CI build" > .env
          echo "NODE_ENV=production" >> .env
          echo "CI=true" >> .env

      - name: Package and Upload to S3 (macOS)
        env:
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          CSC_LINK: ${{ secrets.CSC_LINK }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
        run: npm run package:publish

  deploy-windows:
    runs-on: windows-latest
    timeout-minutes: 30
    environment: env  # 👈 Add this line

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Vite assets
        run: npm run build

      - name: Create dummy .env for CI build
        run: |
          echo "# Dummy .env file for CI build" > .env
          echo "NODE_ENV=production" >> .env
          echo "CI=true" >> .env

      - name: Package and Upload to S3 (Windows)
        run: |
          $env:AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}"
          $env:AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          $env:AWS_REGION="us-east-1"
          npm run package:publish

  notify:
    runs-on: ubuntu-latest
    needs: [deploy-mac, deploy-windows]
    steps:
      - name: Deployment Complete
        run: |
          echo "🎉 Deployment complete for version ${{ github.event.inputs.version }}!"
          echo ""
          echo "📦 Files uploaded to S3:"
          echo "• macOS: https://yeetcode-bucket.s3.amazonaws.com/YeetCode.dmg"
          echo "• Windows: https://yeetcode-bucket.s3.amazonaws.com/YeetCode.exe"
          echo ""
          echo "✅ Ready to update installer links!"
