name: Deploy FastAPI (diff-based)

on:
  workflow_dispatch:
    inputs:
      reason:
        description: "Why are you deploying?"
        required: false
        default: "Manual deployment"

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: env


    steps:
      - name: Checkout code (with commit history)
        uses: actions/checkout@v3
        with:
          fetch-depth: 2  # Needed for HEAD~1 diff to work

      - name: Get list of changed files in scripts/fastapi/
        id: diff
        run: |
          git diff --name-only HEAD~1 HEAD -- scripts/fastapi/ > changed.txt
          cat changed.txt

      - name: Create tarball of only changed files
        run: |
          mkdir -p changed-files
          while read file; do
            mkdir -p changed-files/$(dirname "$file")
            cp "$file" changed-files/"$file"
          done < changed.txt
          tar -czf changed-files.tar.gz -C changed-files .

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Upload and deploy to VPS
        run: |
          scp changed-files.tar.gz changed.txt ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/root/
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
            cd /root/yeetcode-api &&
            tar -xzf /root/changed-files.tar.gz -C . &&
            rm /root/changed-files.tar.gz &&

            # Install requirements if it changed
            if grep -q 'scripts/fastapi/requirements.txt' /root/changed.txt; then
              echo 'requirements.txt changed, installing...'
              source .venv/bin/activate && pip install -r requirements.txt
            else
              echo 'No changes to requirements.txt'
            fi &&

            # Kill and restart FastAPI
            pkill -f 'python3 main.py' || true &&
            nohup bash -c 'source .venv/bin/activate && python3 main.py' > fastapi.log 2>&1 &
          "

      - name: Notify success on Discord
        if: success()
        run: |
          if [ -n "${{ secrets.DISCORD_WEBHOOK }}" ]; then
            curl -H "Content-Type: application/json" \
                -X POST \
                -d '{"content": "✅ YeetCode FastAPI deployed with only changed files!"}' \
                ${{ secrets.DISCORD_WEBHOOK }}
          else
            echo "🔕 DISCORD_WEBHOOK not set, skipping notification."
          fi

      - name: Notify failure on Discord
        if: failure()
        run: |
          if [ -n "${{ secrets.DISCORD_WEBHOOK }}" ]; then
            curl -H "Content-Type: application/json" \
                -X POST \
                -d '{"content": "❌ YeetCode FastAPI deploy failed."}' \
                ${{ secrets.DISCORD_WEBHOOK }}
          else
            echo "🔕 DISCORD_WEBHOOK not set, skipping notification."
          fi
